### PR TITLE
Add path to ansible config file

### PR DESCRIPTION
**Pull request by jonathanheaden**
# Update documentation

The path to the ansible config file is under the ansible folder

## Type Of Change

To help us figure out who should review this PR, please put an X in all the areas that this PR affects.

- [ X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] Test and/or Release
- [ ] User Experience

## Issue Ref (Optional)

Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #

## Notes

Add special notes for your reviewer here.

### CODE REVIEW

**Review by RobReus — APPROVED** [review]
Thanks a lot for your contribution.

**Comment by RobReus** [comment]
@jonathanheaden feel free to join our discord at https://discord.gg/RGvKzVg where there are a lot like-minded people. We're currently working on further improving this project with regards to documentation, automation and tooling.

**Comment by xunholy** [comment]
We'll also need to make this change in the docs repo so it publishes the changes to the website docs if you're okay with that @jonathanheaden .Thanks for contributing!

**Comment by jonathanheaden** [comment]
👍 sounds good to me

**Pull request merged**
