### PR TITLE
Update cloud-config.yml

### PR DESCRIPTION
**Pull request by rmiddle**
Remove SSH Key they shouldn't be in a git hub ever.  Added in US locals to make life easier for people in the US however I left them commented out including them makes it easier for people in the US.

### CODE REVIEW

**Comment by xunholy** [comment]
Thanks for raising this change, although public keys are completely fine to store in source control. With the `locale` and `timezone` fields, we could also possibly add a link to the docs that have a list of all available options to make it easier for others coming through a similar process, happy to hear your thoughts!

**Comment by xunholy** [comment]
@rmiddle to fix DCO you can run this on your local fork

```
git commit --amend --signoff
git push --force-with-lease origin main
```

**Comment by rmiddle** [comment]
I fixed the DCO check.  I did a quick look to find a list of locales but couldn't find a handy list.

**Review by xunholy — APPROVED** [review]
Thanks @rmiddle

**Pull request merged**
